[package]
name = "crabmq"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.95"
dotenvy = "0.15"
log = "0.4.25"
env_logger = "0.11.6"
thiserror = "2.0.11"
uuid = { version = "1", features = ["fast-rng", "v4", "serde"] }
rand = "0.9.0"
